[video]
resolution = [1280, 720]
framerate = 60

[multiplayer]
enable = false
server_host = "127.0.0.1"
server_port = 2000
server_polling_interval = 10

[world_generation]
# resolution = [15360, 8640]
resolution = [3840, 2160]
# seed = 53220
octaves = 15
persistence = 0.5
lacunarity = 2
frequency = 1.0
