[video]
resolution = [800, 800]

[multiplayer]
enable = false
server_host = "127.0.0.1"
server_port = 2000

[world_generation]
seed = 53220
octaves = 15
persistence = 0.5
lacunarity = 2
frequency = 0.004
